[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="locale" type="java.util.Locale" --]
[#-- @ftlvariable name="recipient" type="billiongoods.server.services.notify.Recipient" --]
[#-- @ftlvariable name="messageSource" type="billiongoods.server.MessageFormatter" --]