[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="locale" type="java.util.Locale" --]
[#-- @ftlvariable name="member" type="billiongoods.core.Member" --]

[#-- @ftlvariable name="messageSource" type="billiongoods.server.MessageFormatter" --]

[#-- @ftlvariable name="catalog" type="billiongoods.server.warehouse.Catalog" --]
[#-- @ftlvariable name="section" type="java.lang.String" --]
[#-- @ftlvariable name="department" type="billiongoods.server.web.servlet.mvc.Department" --]

[#-- @ftlvariable name="imageResolver" type="billiongoods.server.services.image.ImageResolver" --]
[#-- @ftlvariable name="personalityContext" type="billiongoods.server.web.security.context.PersonalityContext" --]

[#-- @ftlvariable name="StockState" type="billiongoods.server.warehouse.StockState.static" --]
[#-- @ftlvariable name="ImageSize" type="billiongoods.server.services.image.ImageSize.static" --]
[#-- @ftlvariable name="OrderState" type="billiongoods.server.services.payment.OrderState.static" --]
[#-- @ftlvariable name="MarkupType" type="billiongoods.server.services.price.MarkupType.static" --]
[#-- @ftlvariable name="ProductState" type="billiongoods.server.warehouse.ProductState.static" --]
[#-- @ftlvariable name="ShipmentType" type="billiongoods.server.services.payment.ShipmentType.static" --]
[#-- @ftlvariable name="SortingType" type="billiongoods.server.web.servlet.mvc.warehouse.form.SortingType.static" --]
[#-- @ftlvariable name="AttributeType" type="billiongoods.server.warehouse.AttributeType.static" --]
[#-- @ftlvariable name="GroupType" type="billiongoods.server.warehouse.GroupType.static" --]
[#-- @ftlvariable name="RelationshipType" type="billiongoods.server.warehouse.RelationshipType.static" --]
[#-- @ftlvariable name="TrackingType" type="billiongoods.server.services.tracking.TrackingType.static" --]
[#-- @ftlvariable name="OrderStateUnion" type="billiongoods.server.web.servlet.mvc.privacy.form.OrderStateUnion.static" --]
